# quay.io/toolbx/ubuntu-toolbox:26.04
FROM quay.io/toolbx/ubuntu-toolbox@sha256:e016c22a8772fcaa3c036df552848f95ba16e62ecf2f38295d1194e5d5d0ff28 AS base
COPY ./base-toolbx-ubuntu/toolbox-packages /

ARG DEBIAN_FRONTEND=noninteractive
RUN --mount=type=cache,dst=/var/cache/apt \
    --mount=type=cache,dst=/var/log \
    --mount=type=cache,dst=/var/lib/apt \
    --mount=type=cache,dst=/var/lib/dpkg/updates \
    --mount=type=tmpfs,dst=/tmp \

    sed -Ei 's/^(hosts:.*)(\<files\>)\s*(.*)/\1\2 myhostname \3/' /etc/nsswitch.conf && \
    
    apt-get update -y && \
    apt-get install -y \
        $(cat toolbox-packages | xargs) && \
    rm /toolbox-packages && \

    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/docker && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/flatpak && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/podman && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/rpm-ostree && \
    echo "ALL ALL = (ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    apt-get install -y attr && \
    dpkg-query -W -f='${Package}\n' | while read pkgname; do \
        echo "Setting file attributes for package: $pkgname (chunkah)"; \
        dpkg -L "$pkgname" | while read filepath; do \
            if [ -f "$filepath" ]; then \
                setfattr -n user.component -v "$pkgname" "$filepath" || true; \
            fi; \
        done; \
    done && \
    apt-get remove -y attr


# https://github.com/coreos/chunkah
FROM quay.io/coreos/chunkah:latest AS chunkah

# Rechunk
ARG SOURCE_DATE_EPOCH
ENV SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}
RUN --mount=from=base,src=/,target=/chunkah,ro \
    --mount=type=bind,target=/run/src,rw \
    chunkah build \
    --max-layers 64 \
    --label=com.github.containers.toolbox=true \
    --label=name=devops-toolbox \
    --label=usage="This image is meant to be used with the toolbox or distrobox command" \
    --label=summary="A cloud-native terminal experience powered by Ubuntu" \
    --label=maintainer=fp+oci@forumplayer.dev \
    > /run/src/out.ociarchive

# Deploy final chunked image
FROM oci-archive:out.ociarchive