# quay.io/toolbx/ubuntu-toolbox:25.10
FROM quay.io/toolbx/ubuntu-toolbox@sha256:d0e7551d85d25d98129c28109b2232deb5d098be8170575b64682dad6b457171 AS base
COPY toolbox-packages /

ARG DEBIAN_FRONTEND=noninteractive
RUN --mount=type=cache,dst=/var/cache/apt \
    --mount=type=cache,dst=/var/log \
    --mount=type=cache,dst=/var/lib/apt \
    --mount=type=cache,dst=/var/lib/dpkg/updates \
    --mount=type=tmpfs,dst=/tmp \

    sed -Ei 's/^(hosts:.*)(\<files\>)\s*(.*)/\1\2 myhostname \3/' /etc/nsswitch.conf && \
    
    apt-get update -y && \
    apt-get install -y \
        $(cat toolbox-packages | xargs) && \
    rm /toolbox-packages && \

    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/docker && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/flatpak && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/podman && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/rpm-ostree && \
    echo "ALL ALL = (ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    apt-get install -y attr && \
    dpkg-query -W -f='${Package}\n' | while read pkgname; do \
        echo "Setting file attributes for package: $pkgname (chunkah)"; \
        dpkg -L "$pkgname" | while read filepath; do \
            if [ -f "$filepath" ]; then \
                setfattr -n user.component -v "$pkgname" "$filepath" || true; \
            fi; \
        done; \
    done && \
    apt-get remove -y attr && \
